language: r
cache: packages
r:
- oldrel
- release
- devel
after_success:
- test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'
- bash pkgdown.sh
env:
  global:
    secure: AjMud1+PCn2ltnVvy65CKFEQeRyX6tDcc6Ngwioz5Nnh7/cfp9vq8rHjd2suhtnJcmp9DSHPhRQF0RhR8wBSXSjvJqkXuOC2CtuwvwlHAmT/MOsGoqed2EHMFHwf5dQp+0D4ZjhZLRtIofYiKOAFYzRemepnUw271qrL2r0VLo38YqyGj1KNq8TeFT57LckY++Ozdtduxvmsl7fVgPwBi+UoLf9009xABZzsGju/3+xM0DJ1hP+R+HX8Mdm+DjNuWzuFNbPWdBE0hAERx2Nhr/ETiRUnzSj348kumVGZvFpzCA6RqTo+F7jOuoLnh45fgCtlCgycP7IxIiRzNI3SqTjALc5MKRlv75vOUcltl1dmE7XHOFnMbyeqA7eY2paE0LNrZAVEx32iAQP9cUnVKu14DNI+vZGFKl2kAvaBHPq56pvgAxaH5Wat7i3d4APVUbfFaJGLSgWCRcNN8OWlICKfMEZ/5DTBjooBhlL6IiSJFIPRgU0DQL2unyCeh8Pk4OrFTkm/OFu0mG1T8TRYENvJjpRy/5GspTnfy8vt0zcOdpKxkIHPXgJT5cpsXYrz+ShxSQfDAZfa49gK2O/IrYQm0QSh7TCshvv/iplVUkRb0eD2ulfNH5sgw+4Jhut1YCdaV7avrFymETKezlUECIf9OoLpbcXhh4uNwa9FVQI=
